feature/add_jwt_auth#30
eignatik/petpool pull request #33
Opened 2019-07-27 17:13 UTC by lightway82

Jwt token auth implemented

2019-07-27 17:59 UTC, eignatik requested changes

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthorizedUser.java
> +    return "";
Почему empty string?

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthorizedUser.java
> +    return roles.contains(UserType.BANNED) || roles.contains(UserType.DELETED);
Можно использовать метод из `CollectionUtils#containsAny`

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/JwtCodec.java
> +  public void setJwtKey(Key jwtKey) {
Давай переделаем на инжект через конструктор, это будет легче тестироваться

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/JwtCodec.java
> +  public static class ExpirationTokenException extends Exception {
remove public modifier

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/JwtCodec.java
> +    public ExpirationTokenException(String message) {
remove unnecessary constructors

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/domain/model/user/UserType.java
> +    for (UserType value : UserType.values()) {
What about `CollectionUtils#intersection` ? It's the same functionality, no need to reinvent bikes :)

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/interfaces/auth/facade/AuthFacadeImpl.java
> +  private int expirationToken;
Это tokenExpirationTime, не expirationToken

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/interfaces/auth/facade/AuthFacadeImpl.java
> +  private int expirationRefreshToken;
тоже самое как в предыдущем ^

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/interfaces/auth/facade/AuthFacadeImpl.java
> +  public AuthFacadeImpl(UserService userService) {
4 инжекта через сеттеры - головная боль для тестирования
так как Спринг сам будет использовать конструктор, почему бы не инжектить все через конструктор

2019-07-27 17:59 UTC, eignatik commented on src/test/java/com/petpool/Common.java
> +public class Common {
А что конкретно мы тут тестируем? 
Выглядит как дубликат логики в коде
Если логика в коде поменяется, тесты не упадут и не покажут актуальности кода. Если тут тесты изменятся, это тоже никак не повлияет на программу.
Нам надо тестировать реальный сервис/класс, а не копию логики из него.

2019-07-27 17:59 UTC, eignatik commented on src/test/java/com/petpool/config/security/JwtCodecTest.java
> +    assertTrue(payload.getRoles().stream()
Использование assertTrue без message в assert - плохая практика. Мы никогда не узнаем без дебоша, что пошло не так. А если тест будет падать не регулярно, то это будет головная боль.
Судя по всему результат сравнения это `Assert.assertEquals(actualSize, expectedSize, "MESSAGE")`

2019-07-27 17:59 UTC, eignatik commented on src/test/java/com/petpool/config/security/JwtCodecTest.java
> +    assertTrue(expiration - delta >= 0 && expiration - delta < 1000 * 2L);
Я не представляю, что конкретно тут тестируется. 
Нужен тест `assertEquals(actual, expected, "message if something went wrong")`, отсюда непонятно, что проверяет тест.

2019-07-27 17:59 UTC, eignatik commented on src/test/java/com/petpool/config/security/JwtCodecTest.java
> +    long expiration = 100 * 60 * 1000;
Почему такие числа? Что они значат? Нужен комментарий или более информативное название переменной

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/application/exception/TokenAuthException.java
> +public class TokenAuthException extends AuthenticationException {
Нужно описать, когда и где это исключение выбрасывается. 
Так же убрать лишние конструкторы

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/application/exception/UserNotFoundException.java
> +public class UserNotFoundException extends AuthenticationException {
Описание к исключение
Лишние конструкторы

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthenticationTokenFilter.java
> +        //.map(t-> new String(Base64.getDecoder().decode(t)))
Что за комментарий? Это нужно?

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthenticationTokenProvider.java
> +      throw new TokenAuthException("Other token's parser exception");
Стоит передать`e` как аргумент в конструктор исключения. Иначе как мы будем отлавливать "другие исключения"?

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthorizedUser.java
> +    for (UserType role : roles) {
Опять же можно использовать `CollectionUtils.containsAny`

2019-07-27 17:59 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthorizedUser.java
> +    for (UserType role : roles) {
`CollectionUtils#containsAll`

2019-07-27 18:03 UTC, eignatik commented on src/main/java/com/petpool/interfaces/user/facade/UserImpl.java
> +public class UserImpl implements UserFacade {
UserFacadeImpl будет лучше

2019-07-27 18:03 UTC, eignatik commented on src/main/java/com/petpool/interfaces/user/UserController.java
> +        .orElse(ResponseEntity.status(400).body("User with id ="+id+" not found."));
Выводить на прямую id в body - потенциальная vulnerability. Надо или валидировать id, или не говорить о том, что такой id не найден.
Больше деталей: Endpoints should not be vulnerable to reflected cross-site scripting (XSS) attacks

2019-07-27 18:24 UTC, lightway82 commented on src/main/java/com/petpool/interfaces/user/UserController.java
> +        .orElse(ResponseEntity.status(400).body("User with id ="+id+" not found."));
That only fo debug

2019-07-27 18:24 UTC, lightway82 commented on src/test/java/com/petpool/Common.java
> +public class Common {
Ок, уберу в вики))

2019-07-27 18:24 UTC, lightway82 commented on src/test/java/com/petpool/config/security/JwtCodecTest.java
> +    long expiration = 100 * 60 * 1000;
Время в минутах - в методе оно в минутах принимается.
Ниже в мс

2019-07-27 18:24 UTC, lightway82 commented on src/test/java/com/petpool/config/security/JwtCodecTest.java
> +    assertTrue(expiration - delta >= 0 && expiration - delta < 1000 * 2L);
Это так не проверить, тк после вызова метода, время уже изменится

2019-07-27 18:24 UTC, lightway82 commented on src/test/java/com/petpool/config/security/JwtCodecTest.java
> +    long expiration = 100 * 60 * 1000;
Вместо этого метода сделаю два , чтобы было очевидно, что происходит

2019-07-27 19:37 UTC, lightway82 commented on src/main/java/com/petpool/config/security/AuthorizedUser.java
> +    for (UserType role : roles) {
в случае с  Any - можно заменить цикл на CollectionUtils.containsAny, но он ищет через поиск в массиве, а у меня тут HashSet и contains для него быстрее.
Для All тут вообще нет подходящего по аргументам метода CollectionUtils.containsAll и надо массив в коллекцию преобразовать и опять наткнуться на линейный поиск по массиву.
Предположу, что для маленького массива не большая разница, но ...

2019-07-27 19:38 UTC, lightway82 commented on src/main/java/com/petpool/config/security/AuthorizedUser.java
> +    for (UserType role : roles) {
См выше

2019-07-27 20:02 UTC, lightway82 commented on src/main/java/com/petpool/domain/model/user/UserType.java
> +    for (UserType value : UserType.values()) {
Если внимательно изучить CollectionUtils#intersection, то для данной ситуации он обладает избыточной функциональностью(я сравниваю два Set, а он для любой коллекции и сохраняет еще и одинаковые элементы), создает лишние объекты и возвращает ArrayList, кроме того придется преобразовать массив строк в Set от UserType

2019-07-29 20:05 UTC, eignatik approved these changes

2019-07-29 20:06 UTC, merged