#37 improve auth pipeline
eignatik/petpool pull request #39
Opened 2019-08-04 11:29 UTC by lightway82

2019-08-04 11:31 UTC, lightway82 commented
Допилил аутентификацию. Сделал возврат нескольких видов ошибок и переработал процесс аутентификации( рефакторинг)

2019-08-05 09:19 UTC, eignatik submitted a review, later dismissed

2019-08-05 09:19 UTC, eignatik commented on src/main/java/com/petpool/config/SpringSecurityConfig.java
> +  private static final RequestMatcher ADMIN_API_URL = new AntPathRequestMatcher(
может лучше admin для краткости?

2019-08-05 09:25 UTC, lightway82 commented on src/main/java/com/petpool/config/SpringSecurityConfig.java
> +  private static final RequestMatcher ADMIN_API_URL = new AntPathRequestMatcher(
можно

2019-08-05 17:13 UTC, eignatik requested changes

2019-08-05 17:13 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthenticationTokenProvider.java
> +      throw new BadCredentialsException("Ошибочные данные аутентификации");
мы не хотели бы использовать русский текст в ошибках и так далее) single language для кода

2019-08-05 17:13 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthenticationTokenProvider.java
> +    return authentication.equals(AuthorizedUserAuthentication.class);
Лучше написать `AuthorizedUserAuthentication.class.equals(authentication);` это null safe approach

2019-08-05 17:13 UTC, eignatik commented on src/main/java/com/petpool/config/security/AuthenticationTokenProvider.java
> +    return authentication.equals(AuthorizedUserAuthentication.class);
Я по правде не думаю, что там может придти null, но все же лучше написать так

2019-08-05 17:13 UTC, eignatik commented on src/main/java/com/petpool/config/security/RestAuthenticationEntryPoint.java
> +    if (errorTypeAttribute != null) {
может, стоит объединить два условия в одно? кондишн один и тот же

2019-08-05 17:19 UTC, lightway82 commented on src/main/java/com/petpool/config/security/RestAuthenticationEntryPoint.java
> +    if (errorTypeAttribute != null) {
ты не заметил, это опечатка  ) Там два разных условия. Поправим

2019-08-05 17:31 UTC, eignatik commented on src/main/java/com/petpool/config/security/RestAuthenticationEntryPoint.java
> +    if (errorTypeAttribute != null) {
я заметил, что что-то не так :) так что мы избежали ошибки)

2019-08-05 17:39 UTC, eignatik commented
Поправь плиз code smells :)
https://sonarcloud.io/project/issues?authors=lightway82%40gmail.com&createdAfter=2019-08-02&createdBefore=2019-08-05&id=eignatik_petpool&resolved=false

2019-08-05 20:04 UTC, eignatik approved these changes

2019-08-05 21:37 UTC, merged