#47 Check usernames and emails uniqueness
eignatik/petpool pull request #56
Opened 2019-08-12 12:35 UTC by githelga

1. Добавлено 2 эндпоинта в контроллер UserAuth
2. Тесты добавлены

2019-08-13 18:15 UTC, lightway82 commented on src/main/java/com/petpool/domain/model/user/Person.java
> +    private Set<User> users;
Почему одному Person может соответствовать несколько User ? Как  я понимаю, есть User и для него есть уточнение личных данных и это один к одному.

2019-08-13 18:15 UTC, lightway82 commented on src/main/java/com/petpool/interfaces/validation/UserAuthController.java
> +            return Response.error(ErrorType.BAD_REQUEST,"Request must have parameters");
Фигурные скобки , всегда нужно ставить в условиях.

2019-08-13 18:15 UTC, lightway82 commented on src/main/java/com/petpool/interfaces/validation/UserAuthController.java
> +            return Response.error(ErrorType.BAD_REQUEST,"Request must have parameters");
Фигурные скобки нужно поставить

2019-08-13 18:15 UTC, lightway82 commented on src/test/java/com/petpool/interfaces/validation/UserAuthControllerTest.java
> +        Assert.assertNull(response.getBody().getError(), "Error should be empty");
Зачем две проверки одного и тоже, но по разному?( 
 Assert.assertEquals(response.getBody().getError(), null, "Error should be null");
 Assert.assertNull(response.getBody().getError(), "Error should be empty");
)
Также response.getBody().isErrorPresent() уже говорит о наличии или отсутствии ошибки. Проверять null не нужно

2019-08-13 18:15 UTC, eignatik requested changes

2019-08-13 18:15 UTC, eignatik commented on src/main/java/com/petpool/interfaces/validation/facade/UserAuthFacade.java
> +}
Каждый файл должен заканчиваться пустой строкой. В настойках идеи есть эта опция, так же описана в конвенциях в документации

2019-08-13 18:15 UTC, eignatik commented on src/test/java/com/petpool/interfaces/validation/UserAuthControllerTest.java
> +    private void returnsError_whenParametersIsExisted(ResponseEntity<Response> response) {
snake конвенци именования применима только к тестовым методам, остальные методы должны именоваться CamelCase

2019-08-13 18:15 UTC, eignatik commented on src/main/java/com/petpool/domain/model/user/Person.java
> +    @OneToMany(fetch = FetchType.EAGER)
А почему One To Many? Персона по факту - это расширение User. Одному юзеру - одна персона

2019-08-13 18:15 UTC, eignatik commented on src/main/java/com/petpool/domain/model/user/Person.java
> +    public Person(String firstName, String lastName, String city, String country, Set<User> users) {
Так как мы используем Lombok - правильной практикой будет писать аннотацию `@AllArgsConstructor`

2019-08-13 18:18 UTC, eignatik requested changes

2019-08-13 18:18 UTC, eignatik commented on src/main/java/com/petpool/interfaces/validation/UserAuthController.java
> +    private boolean isNullOrEmpty(String str) {
We have StringUtils in apache-commons with method isNullOrEmpty. Use it instead

2019-08-14 06:14 UTC, githelga commented on src/main/java/com/petpool/domain/model/user/Person.java
> +    private Set<User> users;
может потребоваться при аутентификации через гугл или через фейсбук, например.  Человек один, а аккаунтов может быть много

2019-08-14 17:32 UTC, eignatik commented
@lightway82 мы должны решить, оставим мы OneToMany или OneToOne в Person связь с User. 
Вероятно, в данный момент это не имеет значения, так как изменения для использования регистрации через соцсети затронет большое количество флот, и БД - самая безобидная часть в данный момент, которая если что поменяется быстро.
Делаем наперед это изменение или нет?

2019-08-14 18:25 UTC, lightway82 commented
Если учесть, что PersonService будет основательно перерабатываться, то то что сейчас не важно, но если честно , то этот код будет путать читающих(пока не будет готов другой код), поэтому мне кажется стоит заменить на 1 к 1

2019-08-14 18:29 UTC, lightway82 commented on src/main/java/com/petpool/domain/model/user/Person.java
> +    private Set<User> users;
Может быть вход через разные провайдеры, но это уже дело сервиса аутентификации, а в системе у нас свое представление пользователя. Те человек как бы не вошел, будет всегда одним и тем же юзером. 
Один юзер - одна запись о его данных.

2019-08-14 18:31 UTC, eignatik commented
@githelga сделай тогда 1 к 1

2019-08-16 09:37 UTC, lightway82 commented on src/main/java/com/petpool/interfaces/validation/UserAuthController.java
> +        var isUniqueByUserName = userAuthFacade.isUniqueByEmail(email.trim());
Мы можем вернуть любое серилизуемое значение.  Наш ответ - true или false, запрашивающий знает, что хочет получить. Нет смысла возвращать Map

2019-08-16 09:37 UTC, lightway82 commented on src/main/java/com/petpool/domain/shared/DataBaseInitializer.java
> +
Можешь удалить две закомменченые строки ниже,  они там не нужны, забыли их убрать

2019-08-18 18:59 UTC, eignatik requested changes

2019-08-18 18:59 UTC, eignatik commented on src/main/java/com/petpool/domain/model/user/Person.java
> +public class Person {
Нет default конструктора. Падает ошибка при запуске приложения: 

> org.springframework.orm.jpa.JpaSystemException: No default constructor for entity:  : com.petpool.domain.model.user.Person; nested exception is org.hibernate.InstantiationException: No default constructor for entity:  : com.petpool.domain.model.user.Person] with root cause
org.hibernate.InstantiationException: No default constructor for entity:  : com.petpool.domain.model.user.Person

2019-08-22 07:00 UTC, githelga commented on src/main/java/com/petpool/domain/model/user/Person.java
> +public class Person {
Done

2019-08-22 08:20 UTC, lightway82 commented on src/main/java/com/petpool/interfaces/validation/UserAuthController.java
> +        var isUniqueByUserName = userAuthFacade.isUniqueByEmail(email.trim());
Важное замечание, его нужно поправить

2019-08-22 18:20 UTC, eignatik approved these changes

2019-08-22 18:21 UTC, eignatik commented
👍 Kudos for efforts

2019-08-23 06:48 UTC, merged