Feature/#31
eignatik/petpool pull request #59
Opened 2019-08-17 19:16 UTC by Sam47kon

2019-08-18 19:08 UTC, eignatik requested changes

2019-08-18 19:08 UTC, eignatik commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public static Object[][] parseUserAgent() {
Зачем такое количество входных данных? В чем разница между ними? Я не думаю, что необходимы все кейсы. Достаточно всего несколько (для меня даже больше выглядит, что всего один).
При этом нет негативных сценариев - если нет нормального инпута. Пустая строка как инпут? Какой-нибудь Unknown user agent?

2019-08-18 19:09 UTC, eignatik commented
Именование веток: feature/shorFeatureName#number

2019-08-18 19:11 UTC, Sam47kon commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public static Object[][] parseUserAgent() {
по заданию 9 кейсов же, ок, 2 удалю тогда?
при входных данных null или "something" - возвращается всегда Hacker ...
Я писал об этом Николаю, он сказал, что протестит у себя

2019-08-18 19:19 UTC, eignatik commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public static Object[][] parseUserAgent() {
так как структура каждой строки одинаковая, нет смысла тестировать одинаковые строки с разными цифрами. 
вторую часть разберем

2019-08-19 07:49 UTC, lightway82 commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public static Object[][] parseUserAgent() {
Суть была в том чтобы взять реальные заголовки из браузеров для разных вариантов, проверить, чтобы либа нормально их чекала.

2019-08-19 08:18 UTC, lightway82 commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public static Object[][] parseUserAgent() {
В результате тестов обнаружилось, что либа выдает неоднородные ответы результатов своей работы.

2019-08-19 08:42 UTC, lightway82 submitted a review, later dismissed

2019-08-19 09:55 UTC, eignatik requested changes

2019-08-19 09:55 UTC, eignatik commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public void testParse_(String userAgent, UserAgentParserResult expected) {
Именование тестового метода - что он тестирует? 
parse_forFilledUserAgent_returnsCorrectParsingResult
parse_forEmptyBrowserDescription_returns...
и так далее
Нужны тест кейсы на всю логику, тем более если либа "глупая" и мы написали некоторые врапперы вокруг.
Пожалуйста, пишите тесты.

2019-08-19 09:59 UTC, eignatik requested changes

2019-08-19 09:59 UTC, eignatik commented on src/main/java/com/petpool/application/util/useragent/UserAgentParserStrategyImpl.java
> +  public UserAgentParserResult parse(String userAgent) {
Нужен JavaDoc для метода и класса

2019-08-19 10:38 UTC, lightway82 commented on src/test/java/com/petpool/application/util/useragent/UserAgentParserStrategyImplTest.java
> +  public void testParse_(String userAgent, UserAgentParserResult expected) {
Кейсы все в dataprovider

2019-08-19 10:41 UTC, lightway82 commented on src/main/java/com/petpool/application/util/useragent/UserAgentParserStrategyImpl.java
> +  public UserAgentParserResult parse(String userAgent) {
javadoc есть в реализуемом интерфейсе

2019-08-20 09:30 UTC, eignatik submitted a review, later dismissed

2019-08-20 10:37 UTC, lightway82 approved these changes

2019-08-20 10:37 UTC, merged